

services:
  mongodb:
    image: mongo:7
    container_name: cake-booking-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: cake-booking-redis
    ports:
      - '6379:6379'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cake-booking-backend
    depends_on:
      - mongodb
      - redis
    ports:
      - '5000:5000'
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

volumes:
  mongo_data:
